services:
  parser:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python3 /app/src/parser.py
    restart: always
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./.env:/app/.env
